/**
 * AtroCore Software
 *
 * This source file is available under GNU General Public License version 3 (GPLv3).
 * Full copyright and license information is available in LICENSE.txt, located in the root directory.
 *
 * @copyright  Copyright (c) AtroCore UG (https://www.atrocore.com)
 * @license    GPLv3 (https://www.gnu.org/licenses/)
 */

Espo.define('export:views/export-configurator-item/fields/header-text', 'views/fields/varchar', function (Dep) {

    return Dep.extend({
        init: function () {
            Dep.prototype.init.call(this);

            this.prepareValue();
            this.listenTo(this.model, 'change:name change:' + this.getHeaderPropertyFieldName() + ' change:exportIntoSeparateColumns', () => {
                this.prepareValue();
                this.reRender();
            });
        },

        // this.name is 'headerText1', 'headerText2', etc. (one field per header row, generated by
        // Export\Listeners\Metadata) - its sibling "which property/custom" selector always
        // shares the same numeric suffix.
        getHeaderPropertyFieldName() {
            return 'headerProperty' + this.name.substring('headerText'.length);
        },

        afterRender() {
            Dep.prototype.afterRender.call(this);

            if(this.mode === 'list') {
                this.setReadOnly();
            }
        },

        prepareValue() {
            if (this.mode !== 'list') {
                if (this.model.get('type') === 'Field') {
                    this.prepareFieldValue();
                }
            }
        },

        prepareFieldValue() {
            const headerProperty = this.model.get(this.getHeaderPropertyFieldName());

            if (this.model.get('entityAttributeId')) {
                this.prepareAttributeValue(headerProperty);
                return;
            }

            // 'code' is the field's own raw code - no translation/ajax lookup needed, unlike
            // 'name' below or any other EntityField property (prepareEntityFieldPropertyValue()).
            if (headerProperty === 'code') {
                this.model.set(this.name, this.model.get('name'));
                return;
            }

            if (headerProperty === 'name' || headerProperty === 'tooltipText' || this.model.isNew()) {
                this.prepareTranslatedFieldValue(headerProperty === 'tooltipText' ? 'tooltips' : 'fields');
                return;
            }

            if (headerProperty) {
                this.prepareEntityFieldPropertyValue(headerProperty);
            }
        },

        // name/tooltipText resolve to translated text (the field's label / tooltip, respectively),
        // in the FEED's own configured locale rather than the current user's UI language - matches
        // ExportConfiguratorItem::translateFieldColumnName() server-side.
        prepareTranslatedFieldValue(category) {
            let localeId = null;
            let originField = this.model.get('name');
            if (!this.model.get('exportFeedData')) {
                const exportFeedId = this.model.get('_entityFrom').exportFeedId;
                this.ajaxGetRequest(`ExportFeed/${exportFeedId}`, {}, {async: false}).success(res => {
                    localeId = res.localeId;
                })
            } else {
                localeId = this.model.get('exportFeedData').localeId;
            }

            this.getTranslates(localeId, translates => {
                let columnName = originField;
                if (translates[this.model.get('entity')] && translates[this.model.get('entity')][category] && translates[this.model.get('entity')][category][originField]) {
                    columnName = translates[this.model.get('entity')][category][originField];
                } else if (translates['Global'] && translates['Global'][category] && translates['Global'][category][originField]) {
                    columnName = translates['Global'][category][originField];
                }
                this.model.set(this.name, columnName);
            });
        },

        // Any other EntityField property (type/pattern/default/defaultUnit/foreignCode/...) -
        // already-loaded client-side metadata has it, no need for a round trip. foreignCode isn't
        // a literal field key though (it's derived from the field's own link defs - see
        // Atro\Repositories\EntityField::prepareItem()), so it needs its own lookup.
        prepareEntityFieldPropertyValue(headerProperty) {
            const entityType = this.model.get('entity');
            const fieldName = this.model.get('name');

            const value = headerProperty === 'foreignCode'
                ? this.getMetadata().get(`entityDefs.${entityType}.links.${fieldName}.foreign`)
                : this.getMetadata().get(`entityDefs.${entityType}.fields.${fieldName}.${headerProperty}`);

            this.model.set(this.name, value || '');
        },

        // Attribute items (entityAttributeId set): 'name' has an already-materialized fast path
        // via fieldDefs.label (no ajax - fieldDefs is the target entity's own pseudo-field defs,
        // whose label already reflects the attribute's translated name). Every other property
        // (systemName, tooltip, a custom field, a link/linkMultiple field, ...) has no such cache,
        // so it's resolved by fetching the Attribute record itself - mirroring
        // ExportConfiguratorItem::resolveAttributePropertyColumnName() server-side.
        prepareAttributeValue(headerProperty) {
            if (!headerProperty || headerProperty === 'custom') {
                return;
            }

            if (headerProperty === 'name' && this.model.get('fieldDefs')) {
                this.model.set(this.name, this.model.get('fieldDefs').label);
                return;
            }

            const attributeId = this.model.get('entityAttributeId');
            const propertyType = this.getMetadata().get(`entityDefs.Attribute.fields.${headerProperty}.type`);

            this.ajaxGetRequest(`Attribute/${attributeId}`, {}, {async: false}).success(res => {
                let value = res[headerProperty];

                if (propertyType === 'link') {
                    value = res[headerProperty + 'Name'];
                } else if (propertyType === 'linkMultiple') {
                    value = Object.values(res[headerProperty + 'Names'] || {}).join(', ');
                }

                this.model.set(this.name, value || '');
            });
        },

        getTranslates(locale, callback) {
            this.ajaxGetRequest(`i18n`, {locale: locale}).then(responseData => {
                callback(responseData);
            });
        },

    })
});
