/**
 * AtroCore Software
 *
 * This source file is available under GNU General Public License version 3 (GPLv3).
 * Full copyright and license information is available in LICENSE.txt, located in the root directory.
 *
 * @copyright  Copyright (c) AtroCore UG (https://www.atrocore.com)
 * @license    GPLv3 (https://www.gnu.org/licenses/)
 */

Espo.define('export:views/export-configurator-item/fields/header-text', 'views/fields/varchar', function (Dep) {

    // Shared across every header-text field instance (one per header row, per item) - several
    // rows of the same item, or several items using the same attribute, would otherwise each
    // re-fetch the identical Attribute record.
    const attributeCache = {};

    return Dep.extend({
        init: function () {
            Dep.prototype.init.call(this);

            this.prepareValue();
            this.listenTo(this.model, 'change:name change:' + this.getHeaderPropertyFieldName() + ' change:exportIntoSeparateColumns', () => {
                this.prepareValue();
                this.reRender();
            });
        },

        // this.name is 'headerText1', 'headerText2', etc. (one field per header row, generated by
        // Export\Listeners\Metadata) - its sibling "which property/custom" selector always
        // shares the same numeric suffix.
        getHeaderPropertyFieldName() {
            return 'headerProperty' + this.name.substring('headerText'.length);
        },

        afterRender() {
            Dep.prototype.afterRender.call(this);

            if (this.mode === 'list') {
                this.setReadOnly();
            }
        },

        prepareValue() {
            if (this.mode !== 'list') {
                if (this.model.get('type') === 'Field') {
                    this.prepareFieldValue();
                }
            }
        },

        prepareFieldValue() {
            const headerProperty = this.model.get(this.getHeaderPropertyFieldName());

            if (headerProperty === 'custom') {
                this.prepareCustomValue();
                return;
            }

            if (this.model.get('entityAttributeId')) {
                this.prepareAttributeValue(headerProperty);
                return;
            }

            // 'code' is the field's own raw code - no translation/ajax lookup needed, unlike
            // 'name' below or any other EntityField property (prepareEntityFieldPropertyValue()).
            if (headerProperty === 'code') {
                this.model.set(this.name, this.model.get('name'));
                return;
            }

            if (headerProperty === 'name' || headerProperty === 'tooltipText' || this.model.isNew()) {
                this.prepareTranslatedFieldValue(headerProperty === 'tooltipText' ? 'tooltips' : 'fields');
                return;
            }

            if (headerProperty) {
                this.prepareEntityFieldPropertyValue(headerProperty);
            }
        },

        // 'custom' is free text the user edits - only seed it once, when still empty (e.g. right
        // after switching a row to 'custom'), with the item's own name as a sensible starting
        // point. Never overwrite it afterward - unlike the other branches, which recompute on
        // every relevant model change.
        prepareCustomValue() {
            const value = this.model.get('data')?.[this.name];
            if (value) {
                this.model.set(this.name, value);
            }
        },

        // The feed's own configured locale, not the current user's UI language.
        getExportFeedLocaleId() {
            if (this.model.get('exportFeedData')) {
                return this.model.get('exportFeedData').localeId;
            }

            let localeId = null;
            const exportFeedId = this.model.get('_entityFrom').exportFeedId;
            this.ajaxGetRequest(`ExportFeed/${exportFeedId}`, {}, { async: false }).success(res => {
                localeId = res.localeId;
            })

            return localeId;
        },

        // Mirrors ExportConfiguratorItem::resolveLocalizedFieldName() server-side: the locale-
        // specific column name (e.g. "nameDeDe") for $fieldName on $scope, when $localeId maps to
        // a real, active input language and the field is itself multilang there. Falls back to
        // $fieldName unchanged otherwise.
        getLocalizedFieldName(localeId, scope, fieldName) {
            if (!localeId || !this.getMetadata().get(`entityDefs.${scope}.fields.${fieldName}.isMultilang`)) {
                return fieldName;
            }

            let languageCode = null;
            $.each(this.getConfig().get('referenceData')?.Locale ?? {}, (key, locale) => {
                if (locale.id === localeId) {
                    languageCode = locale.languageCode;
                }
            });

            if (!languageCode) {
                return fieldName;
            }

            const mainLanguage = this.getConfig().get('mainLanguage') || '';
            if (languageCode.toLowerCase() === mainLanguage.toLowerCase()) {
                return fieldName;
            }

            const inputLanguageList = this.getConfig().get('inputLanguageList') || [];
            if (!inputLanguageList.includes(languageCode)) {
                return fieldName;
            }

            const suffix = languageCode.toLowerCase().split('_').map(part => part.charAt(0).toUpperCase() + part.slice(1)).join('');

            return fieldName + suffix;
        },

        getAttribute(attributeId) {
            if (!attributeCache[attributeId]) {
                this.ajaxGetRequest(`Attribute/${attributeId}`, {}, { async: false }).success(res => {
                    attributeCache[attributeId] = res;
                });
            }

            return attributeCache[attributeId];
        },

        // Fetches the related record directly and reads its (localized) field - the Attribute
        // response's own "{property}Name" virtual field is resolved using the current request's
        // locale, not the export feed's configured one, so it can't be read off that same response.
        // Falls back to the base (unlocalized) value when the localized one is empty, e.g. no
        // translation was ever entered for that particular record.
        getLocalizedRelatedValue(entityType, id, fieldName, localeId) {
            const localizedFieldName = this.getLocalizedFieldName(localeId, entityType, fieldName);

            let value = null;
            this.ajaxGetRequest(`${entityType}/${id}`, {}, { async: false }).success(res => {
                value = res[localizedFieldName] || res[fieldName];
            });

            return value;
        },

        // name/tooltipText resolve to translated text (the field's label / tooltip, respectively),
        // in the FEED's own configured locale rather than the current user's UI language - matches
        // ExportConfiguratorItem::translateFieldColumnName() server-side.
        prepareTranslatedFieldValue(category) {
            let originField = this.model.get('name');
            const localeId = this.getExportFeedLocaleId();

            this.getTranslates(localeId, translates => {
                let columnName = originField;
                if (translates[this.model.get('entity')] && translates[this.model.get('entity')][category] && translates[this.model.get('entity')][category][originField]) {
                    columnName = translates[this.model.get('entity')][category][originField];
                } else if (translates['Global'] && translates['Global'][category] && translates['Global'][category][originField]) {
                    columnName = translates['Global'][category][originField];
                }
                this.model.set(this.name, columnName);
            });
        },

        // Any other EntityField property (type/pattern/default/defaultUnit/foreignCode/...) -
        // already-loaded client-side metadata has it, no need for a round trip. foreignCode isn't
        // a literal field key though (it's derived from the field's own link defs - see
        // Atro\Repositories\EntityField::prepareItem()), so it needs its own lookup.
        prepareEntityFieldPropertyValue(headerProperty) {
            const entityType = this.model.get('entity');
            const fieldName = this.model.get('name');

            const value = headerProperty === 'foreignCode'
                ? this.getMetadata().get(`entityDefs.${entityType}.links.${fieldName}.foreign`)
                : this.getMetadata().get(`entityDefs.${entityType}.fields.${fieldName}.${headerProperty}`);

            this.model.set(this.name, value || '');
        },

        // Attribute items (entityAttributeId set): 'name' has an already-materialized fast path
        // via fieldDefs.label (no ajax - fieldDefs is the target entity's own pseudo-field defs,
        // whose label already reflects the attribute's translated name). Every other property
        // (systemName, tooltip, a custom field, a link/linkMultiple field, ...) has no such cache,
        // so it's resolved by fetching the Attribute record itself - mirroring
        // ExportConfiguratorItem::resolveAttributePropertyColumnName() server-side.
        prepareAttributeValue(headerProperty) {
            // 'custom' is intercepted earlier, in prepareFieldValue() - this only sees the
            // remaining resolvable properties, plus possibly empty/not-yet-set.
            if (!headerProperty) {
                return;
            }

            if (headerProperty === 'name' && this.model.get('fieldDefs')) {
                this.model.set(this.name, this.model.get('fieldDefs').label);
                return;
            }

            const attributeId = this.model.get('entityAttributeId');
            const propertyType = this.getMetadata().get(`entityDefs.Attribute.fields.${headerProperty}.type`);
            const localeId = this.getExportFeedLocaleId();

            const res = this.getAttribute(attributeId);
            if (!res) {
                return;
            }

            let value = res[headerProperty];

            if (propertyType === 'link') {
                const relatedEntityType = this.getMetadata().get(`entityDefs.Attribute.links.${headerProperty}.entity`)
                    || this.getMetadata().get(`entityDefs.Attribute.fields.${headerProperty}.entity`);
                const relatedId = res[headerProperty + 'Id'];

                value = relatedId && relatedEntityType
                    ? this.getLocalizedRelatedValue(relatedEntityType, relatedId, 'name', localeId)
                    : null;
                if (!value) {
                    value = res[headerProperty + 'Name'];
                }
            } else if (propertyType === 'linkMultiple') {
                value = Object.values(res[headerProperty + 'Names'] || {}).join(', ');
            } else {
                const localizedField = this.getLocalizedFieldName(localeId, 'Attribute', headerProperty);
                value = res[localizedField] || res[headerProperty];
            }

            this.model.set(this.name, value || '');
        },

        getTranslates(locale, callback) {
            this.ajaxGetRequest(`i18n`, { locale: locale }).then(responseData => {
                callback(responseData);
            });
        },

    })
});
